import type { Rule } from "./types.js";

export const DEFAULT_FORBID: Rule[] = [
	{
		id: "forbid.privilege-escalation",
		description: "sudo/su/doas",
		kind: "bash",
		severity: "forbid",
		match: { argv0: ["sudo", "su", "doas"] },
		reason: "Privilege escalation is not permitted.",
	},
	{
		id: "forbid.rm-rf-root",
		description: "rm -rf on /, ~, or $HOME",
		kind: "bash",
		severity: "forbid",
		match: {
			argv0: "rm",
			argvAny: ["-rf", "-fr", "--recursive"],
			argvPattern: "(^|\\s)(/|~|\\$HOME)(\\s|$)",
		},
		reason: "Recursive delete of system or home root is forbidden.",
	},
	{
		id: "forbid.dd-device",
		description: "dd writing to a device",
		kind: "bash",
		severity: "forbid",
		match: { argv0: "dd", argvPattern: "of=/dev/" },
		reason: "dd to a device is forbidden.",
	},
	{
		id: "forbid.mkfs",
		description: "mkfs*",
		kind: "bash",
		severity: "forbid",
		match: { argvPattern: "^mkfs" },
		reason: "Filesystem creation is forbidden.",
	},
	{
		id: "forbid.fork-bomb",
		description: "fork bomb pattern",
		kind: "bash",
		severity: "forbid",
		match: { argvPattern: ":\\(\\)\\{.*:\\|:&.*\\};:" },
		reason: "Fork bomb pattern detected.",
	},
	{
		id: "forbid.curl-pipe-shell",
		description: "downloader piped into a shell",
		kind: "bash",
		severity: "forbid",
		match: { custom: "curl-pipe-shell" },
		reason: "Piping a download directly into a shell is forbidden.",
	},
	{
		id: "forbid.reverse-shell",
		description: "reverse/bind shell via nc/ncat or /dev/tcp",
		kind: "bash",
		severity: "forbid",
		match: { custom: "reverse-shell" },
		reason: "Reverse-shell pattern detected.",
	},
	{
		id: "forbid.variable-argv0",
		description: "program name is a variable reference",
		kind: "bash",
		severity: "forbid",
		match: { argvPattern: "^\\$" },
		reason: "Program name from a variable cannot be statically verified.",
	},
	{
		id: "forbid.credential-read",
		description: "read of credential files",
		kind: "path-read",
		severity: "forbid",
		paths: ["~/.ssh/id_*", "~/.aws/credentials", "~/.gnupg/**", "~/.config/gh/hosts.yml"],
		reason: "Reading credential files is forbidden.",
	},
	{
		id: "forbid.system-write",
		description: "writes to system paths",
		kind: "path-write",
		severity: "forbid",
		paths: ["/etc/**", "/System/**", "/usr/**", "/boot/**", "/bin/**", "/sbin/**"],
		reason: "Writes to system paths are forbidden.",
	},
	{
		id: "forbid.path-escape-write",
		description: "write outside project root",
		kind: "path-write",
		severity: "forbid",
		match: { custom: "escapes-project" },
		reason: "Write escapes the project root.",
	},
	{
		id: "forbid.eval",
		description: "eval builtin",
		kind: "bash",
		severity: "forbid",
		match: { argv0: "eval" },
		reason: "eval is forbidden (opaque payload, defense-in-depth).",
	},
];

export const DEFAULT_ASK: Rule[] = [
	{
		id: "ask.git-push-default",
		description: "git push to default branch",
		kind: "bash",
		severity: "ask",
		match: { argv0: "git", argvAll: ["push"], custom: "default-branch" },
		reason: "Pushing to the default branch requires approval.",
	},
	{
		id: "ask.git-push-force",
		description: "git push --force",
		kind: "bash",
		severity: "ask",
		match: { argv0: "git", argvAll: ["push"], custom: "force" },
		reason: "Force push requires approval.",
	},
	{
		id: "ask.git-merge",
		description: "git merge",
		kind: "bash",
		severity: "ask",
		match: { argv0: "git", argvAll: ["merge"] },
		reason: "git merge requires approval.",
	},
	{
		id: "ask.git-destructive",
		description: "destructive git commands",
		kind: "bash",
		severity: "ask",
		match: {
			argv0: "git",
			argvPattern: "\\b(reset\\s+--hard|clean\\s+-fd|branch\\s+-D|tag\\s+-d)\\b",
		},
		reason: "Destructive git command requires approval.",
	},
	{
		id: "ask.pkg-publish",
		description: "package publish",
		kind: "bash",
		severity: "ask",
		match: {
			argvPattern:
				"\\b(npm|yarn|pnpm|bun)\\s+publish\\b|\\bcargo\\s+publish\\b|\\bgh\\s+release\\s+create\\b",
		},
		reason: "Publishing a package requires approval.",
	},
	{
		id: "ask.pkg-install-new",
		description: "install a new dependency (npm/yarn/pnpm/bun)",
		kind: "bash",
		severity: "ask",
		match: { custom: "pkg-install" },
		reason: "Adding a new dependency requires approval.",
	},
	{
		id: "ask.pip-install-new",
		description: "pip install of a package",
		kind: "bash",
		severity: "ask",
		match: { custom: "pip-install" },
		reason: "pip install of a package requires approval.",
	},
	{
		id: "ask.cargo-add",
		description: "cargo add",
		kind: "bash",
		severity: "ask",
		match: { custom: "cargo-add" },
		reason: "cargo add requires approval.",
	},
	{
		id: "ask.sensitive-write",
		description: "write to secrets/CI/key files",
		kind: "path-write",
		severity: "ask",
		paths: [
			".env",
			".env.*",
			"*.pem",
			"*.key",
			"**/secrets/**",
			".git/config",
			".github/workflows/**",
		],
		reason: "Writing to a sensitive path requires approval.",
	},
	{
		id: "ask.sensitive-read",
		description: "read of secrets/key files",
		kind: "path-read",
		severity: "ask",
		paths: [".env", ".env.*", "*.pem", "*.key", "**/secrets/**"],
		reason: "Reading a sensitive path requires approval.",
	},
	{
		id: "ask.mass-delete",
		description: "mass delete via find or xargs",
		kind: "bash",
		severity: "ask",
		match: { argvPattern: "\\bfind\\b.*-delete\\b|\\bxargs\\b.*\\brm\\b" },
		reason: "Mass file deletion requires approval.",
	},
	{
		id: "ask.net-download-exec",
		description: "curl/wget of a scriptable file",
		kind: "bash",
		severity: "ask",
		match: { argvPattern: "\\b(curl|wget)\\b.*\\.(sh|bash|py|js|pl|rb)(\\s|$)" },
		reason: "Downloading a script requires approval.",
	},
	{
		id: "ask.dynamic-interpreter",
		description: "python -c, node -e, etc.",
		kind: "bash",
		severity: "ask",
		match: { argvPattern: "^(python3?|node|perl|ruby)\\s+(-c|-e)\\b" },
		reason: "Dynamic interpreter contents are opaque — approval required.",
	},
	{
		id: "ask.path-manip",
		description: "env prefix (VAR=val)",
		kind: "bash",
		severity: "ask",
		match: { argv0: ["env"] },
		reason: "env prefix can alter the PATH — approval required.",
	},
];
